research_topic:
  description: >
    Research the topic {topic} and points listed in {points} and gather latest information in the past two years with the search tool and the scrape tool. 
    Summarize the main points for the topic writer to write a section of 2-3 paragraphs.
    Make connections to the other sections of the full report: {sections}, but no redundant in content.
  expected_output: >
    A list of insights and key points about the topic {topic}.
  agent: "topic_researcher"

write_topic:
  description: >
    Write a section about {topic} based on the insights and key points gathered by the topic researcher agent.
    Cite the references provided by the topic researcher agent.
    Include plots and tables when necessary.
    Ensure the section adheres to the main topic {query} and cover points listed in {points}.
    These are all the other sections of the full report: {sections}
  expected_output: >
    A well-written and well-structured section with the most important and accurate insights on {topic}. The section should have 2 or 3 paragraphs.
  agent: "topic_writer"

validate_task:
    description: >
        Proofread the given report for fact checking and grammatical errors. 
        Verify the accuracy of information and cross-check facts with reliable sources published no later than the data source in given report using the search tool, scrape tool.
        Verify that the content relevant to the query of this report: {query} and cover points listed in {points}.
    expected_output: >
        A well-written investigation report, ready for publication, each section should have 2 or 3 paragraphs.
    agent: "validate_agent"